esphome:
  name: cyd1
  friendly_name: cyd1

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxGcIbaqCAf4JOhfv60nmzg="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.page.show: pg_main
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.page.show: pg_offline

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxx8371419b74d8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.58
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

  ap:
    ssid: "Cyd1 Fallback Hotspot"
    password: "xxxxxxxxxxxx"

captive_portal:

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
  - platform: homeassistant
    id: spot1
    name: "spot1 button"
    entity_id: light.tuya_rgbw_light
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: spot1_btn
          state:
            checked: !lambda return x;
  - platform: homeassistant
    id: spot3
    name: "spot3 button"
    entity_id: light.tuya_rgbw3_light
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: spot3_btn
          state:
            checked: !lambda return x;
  - platform: homeassistant
    id: fan
    name: "fan button"
    entity_id: switch.teclastar1_relay
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: fan_btn
          state:
            checked: !lambda return x;

switch:
  - platform: template
    name: "next screen"
    turn_on_action:
      then:
        - lvgl.page.next

spi:
  - id: tft_spi
    clk_pin: GPIO14 #18
    mosi_pin: GPIO13 #23
    miso_pin: GPIO12

  - id: touch_spi
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

display:
  - platform: ili9xxx
    id: my_display
    model: ILI9341 
    spi_id: tft_spi
    cs_pin: GPIO15
    dc_pin: GPIO2 
    dimensions: 
      height: 240
      width: 320
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false
    invert_colors: false
    auto_clear_enabled: false
    color_palette: 8BIT
    update_interval: never

touchscreen:
  - platform: xpt2046
    id: cyd_touchscreen
    spi_id: touch_spi
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    update_interval: 50ms
    calibration:
      x_min: 180
      x_max: 3700
      y_min: 235
      y_max: 3800
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: false
    threshold: 400

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
    frequency: 5000 Hz

  - platform: ledc
    pin: GPIO4 # Red
    id: led_red_output
    inverted: true # Invert logic because it's active low

  - platform: ledc
    pin: GPIO16 # Green
    id: led_green_output
    inverted: true

  - platform: ledc
    pin: GPIO17 # Blue
    id: led_blue_output
    inverted: true

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON

  - platform: rgb
    name: Onboard RGB LED
    id: onboard_rgb_led
    red: led_red_output
    green: led_green_output
    blue: led_blue_output

sensor:
  - platform: homeassistant
    id: temp1
    entity_id: weather.forecast_cramer
    attribute: temperature
    accuracy_decimals: 2
    on_value:
      - lvgl.arc.update:
          id: temp_arc
          value: !lambda return x;
      - lvgl.label.update:
          id: temp_label
          text:
            format: "%.1f°C"
            args: [ 'x' ]

  - platform: adc
    pin: GPIO34 # Connected to the LDR
    id: ldr_sensor
    name: "Ambient Light Sensor"
    update_interval: 5s
    attenuation: 2.5db # Reads 0.078V when illuminated, up to 1.5V when in darkness

image:
  - file: "ghf_2.png"
    id: ghf_2
    resize: 320x240
    type: RGB565

lvgl:
  displays: my_display
  buffer_size: 25%

  pages:
    - id: pg_offline
      bg_color: black
      widgets:
        - label:
            align: CENTER
            text_color: red
            text_font: montserrat_24
            text: 'Offline...'

    - id: pg_main
      bg_color: black
      widgets:
        - obj: # thermometer container
            width: 160
            height: 130
            align: TOP_LEFT
            bg_color: black
            border_width: 0
            pad_all: 0
            widgets:
              - arc:
                  id: temp_arc
                  min_value: -5
                  max_value: 45
                  arc_color: blue
                  align: CENTER
                  widgets:
                    - label:
                        id: temp_label
                        align: CENTER
                        text_color: yellow
                        text_font: montserrat_22
        - obj: # clock container
            id: clock_container
            width: 160
            height: 130
            align: TOP_RIGHT
            bg_color: black
            border_width: 0
            pad_all: 0
            widgets:
              - meter:
                  align: CENTER
                  bg_color: 0x101010
                  border_width: 0
                  text_color: gray
                  scales:
                    - range_from: 0 # minutes scale
                      range_to: 60
                      angle_range: 360
                      rotation: 270
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: minutes_hand
                            width: 3
                            color: yellow #0xa6a6a6
                            r_mod: -4
                    - range_from: 1 # hours scale
                      range_to: 12
                      angle_range: 330
                      rotation: 300
                      ticks:
                        width: 2
                        count: 12
                        length: 5
                        color: red
                    - range_from: 3 # hours scale for labels (3,6,9,12)
                      range_to: 12
                      angle_range: 270
                      rotation: 0
                      ticks:
                        count: 10
                        width: 0
                        length: 0
                        major:
                          stride: 3
                          width: 4
                          length: 10
                          color: blue 
                          label_gap: 10
                    - range_from: 0 # hi-res hours scale for hand
                      range_to: 720
                      angle_range: 360
                      rotation: 270
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: hours_hand
                            width: 5
                            color: yellow #0xa6a6a6
                            r_mod: -15
        - obj: # buttons container
            width: 100%
            height: 36%
            align_to:
              id: clock_container
              align: OUT_BOTTOM_RIGHT
            bg_color: black
            border_width: 1
            pad_all: 4
            text_font: montserrat_18
            widgets:
              - button:
                  width: 49%
                  height: 47%
                  align: TOP_LEFT
                  id: spot1_btn
                  widgets:
                    - label:
                        text: "spot1"
                        align: CENTER
                  on_click:
                    - homeassistant.action:
                        action: light.toggle
                        data:
                          entity_id: light.tuya_rgbw_light
                          brightness_pct: "100"
                          kelvin: "6500"
              - button:
                  width: 49%
                  height: 47%
                  align: TOP_RIGHT
                  id: spot3_btn
                  widgets:
                    - label:
                        text: "spot3"
                        align: CENTER
                  on_click:
                    - homeassistant.action:
                        action: light.toggle
                        data:
                          entity_id: light.tuya_rgbw3_light
                          brightness_pct: "100"
                          kelvin: "2000"
              - button:
                  width: 49%
                  height: 47%
                  align: BOTTOM_LEFT
                  id: fan_btn
                  widgets:
                    - label:
                        text: "fan"
                        align: CENTER
                  on_click:
                    - homeassistant.action:
                        action: switch.toggle
                        data:
                          entity_id: switch.teclastar1_relay
              - dropdown:
                  width: 49%
                  height: 47%
                  align: BOTTOM_RIGHT
                  bg_color: 0x8080ff #celeste?
                  text_color: white
                  options:
                    - green
                    - blue
                    - dark
                    - cold white
                    - warm white
                    - silence
                  on_change:
                    - homeassistant.action:
                        action: scene.turn_on
                        data:
                          entity_id: !lambda |-
                            static const char* scenes[] = {
                              "scene.green","scene.blue","scene.dark",
                              "scene.cold_white","scene.warm_white",
                              "scene.silence"
                            };
                            return scenes[x];                   
        - obj: # navigation container
            width: 100%
            height: 10%
            align: BOTTOM_MID
            bg_color: black
            border_width: 0
            pad_all: 2
            text_font: montserrat_14
            widgets:
              - button: #previous page
                  width: 33%
                  height: 97%
                  align: TOP_LEFT
                  widgets:
                    - label:
                        text: "\uF053"
                        align: CENTER
                  on_click:
                    then:
                      lvgl.page.show: pg_img1
              - button: #home page
                  width: 33%
                  height: 97%
                  align: TOP_MID
                  widgets:
                    - label:
                        text: "\uF015"
                        align: CENTER
                  on_click:
                    then:
                      lvgl.page.show: pg_main
              - button: #next page
                  width: 33%
                  height: 97%
                  align: TOP_RIGHT
                  widgets:
                    - label:
                        text: "\uF054"
                        align: CENTER
                  on_click:
                    then:
                      lvgl.page.show: pg_clock

    - id: pg_img1
      widgets: 
        - image:
            src: ghf_2
            align: CENTER
        - obj: # navigation container
            width: 20%
            height: 10%
            align: BOTTOM_RIGHT
            bg_color: black
            border_width: 0
            pad_all: 2
            text_font: montserrat_14
            widgets:
              - button: #home page
                  width: 100%
                  height: 97%
                  align: CENTER
                  widgets:
                    - label:
                        text: "\uF015"
                        align: CENTER
                  on_click:
                    then:
                      lvgl.page.show: pg_main

    - id: pg_clock
      bg_color: black
      widgets:
        - obj: # clock container
            height: SIZE_CONTENT
            width: 240
            align: CENTER
            pad_all: 0
            border_width: 0
            bg_color: black
            widgets:
              - meter: # clock face
                  height: 220
                  width: 220
                  align: CENTER
                  #bg_opa: TRANSP
                  bg_color: 0x101010
                  border_width: 0
                  text_color: white
                  scales:
                    - range_from: 0 # minutes scale
                      range_to: 60
                      angle_range: 360
                      rotation: 270
                      ticks:
                        width: 1
                        count: 61
                        length: 10
                        color: green
                      indicators:
                        - line:
                            id: minute_hand
                            width: 3
                            color: 0xa6a6a6
                            r_mod: -4
                            value: 0
                    - range_from: 1 # hours scale for labels
                      range_to: 12
                      angle_range: 330
                      rotation: 300
                      ticks:
                        width: 1
                        count: 12
                        length: 1
                        major:
                          stride: 1
                          width: 4
                          length: 10
                          color: 0xC0C0C0
                          label_gap: 12
                    - range_from: 0 # hi-res hours scale for hand
                      range_to: 720
                      angle_range: 360
                      rotation: 270
                      ticks:
                        count: 0
                      indicators:
                        - line:
                            id: hour_hand
                            width: 5
                            color: 0xa6a6a6
                            r_mod: -30
                            value: 0
              - label:
                  id: day_label
                  align: CENTER
                  text_color: yellow
                  y: -30
              - label:
                  id: date_label
                  align: CENTER
                  text_color: yellow
                  y: 30
        - obj: # navigation container
            width: 20%
            height: 10%
            align: BOTTOM_RIGHT
            bg_color: black
            border_width: 0
            pad_all: 2
            text_font: montserrat_14
            widgets:
              - button: #home page
                  width: 100%
                  height: 97%
                  align: CENTER
                  widgets:
                    - label:
                        text: "\uF015"
                        align: CENTER
                  on_click:
                    then:
                      lvgl.page.show: pg_main

time:
  - platform: homeassistant
    id: time_comp
    timezone: "UTC+3"
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(time_comp).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(time_comp).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.indicator.update:
          id: minutes_hand
          value: !lambda |-
            return id(time_comp).now().minute;
      - lvgl.indicator.update:
          id: hours_hand
          value: !lambda |-
            auto now = id(time_comp).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.label.update:
          id: date_label
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[8];
            auto now = id(time_comp).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(time_comp).now().day_of_week - 1];          
